### ISSUE TITLE
Improving the efficiency of the formula for Sierpinski's constant

### ISSUE THREAD

**Issue by MillaBasset** [Mysticial/y-cruncher-Formulas#5]
More than two years ago, I added [this](https://github.com/Mysticial/y-cruncher-Formulas/blob/e70c3813a25108bb7050040ea6148c78d0346f0a/User%20Formulas/Sierpinski%20-%20Direct.cfg) basic formula for Sierpinski's constant. The EulerGamma computation uses a few ArcCoth computations; in fact, the same ones used for calculating Log(2). Is there a way for the EulerGamma implementation to change such that pre-computed ArcCoth values can be supplied to make the formula faster?

(Also, it may be a slight improvement in the formula to calculate EulerGamma before Log(Gamma(1/4)), the current first term in the LinearCombination.)

**Comment by Mysticial** [comment]
There isn't. Given how slow EulerGamma is compared to the ArcCoths and how niche this was, I didn't think it was necessary.

For ram only mode, the having multiple outputs also complicates the memory management. OTOH, the reverse is easier (pre-computing the ArcCoths and passing it in), though it will increase memory usage since it would need to be held through the EulerGamma series computation which is huge.

**Comment by MillaBasset** [comment]
It *is* niche, yeah. It is only useful for the Sierpinski constant, but if this did happen in the future, however unlikely it may be, definitely would speed up computation for a large number of digits.
